# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: "python:latest" 
#commands to run in the Docker container before starting each job.
before_script:
  - python --version
  - pip install -r requirements.txt
# different stages in the pipeline
stages:
  - Static Analysis
  - Test
#defines the job in Static Analysis
pylint:
  stage: Static Analysis
  allow_failure: true
  tags:
    - python
  script:
  - pylint -d W0401 -d W0614 src/

pytest:
  stage: Test
  tags:
    - python
  script:
  - cd src
  - python3 -m unittest discover tests/
  only:
  - merge_requests
